export const ConstListSourcing = {
  SET_DATA: "SOURCING_SELECTION_SET_DATA",
  SET_FILTER: "SOURCING_SELECTION_SET_FILTER",
  FAILED: "SOURCING_SELECTION_FAILED",
  CLEAR: "SOURCING_SELECTION_CLEAR",
  LOADING: "SOURCING_SELECTION_LOADING",
};
