export const ConstRequestBid = {
  SET_DATA: "REQUEST_BID_SET_DATA",
  SET_FILTER: "REQUEST_BID_SET_FILTER",
  FAILED: "REQUEST_BID_FAILED",
  CLEAR: "REQUEST_BID_CLEAR",
  LOADING: "REQUEST_BID_LOADING",
};
