export const AUTHENTICATE = "AUTHENTICATE";
export const DEAUTHENTICATE = "DEAUTHENTICATE";

// PPCR
export const NEXT_PPCR_FORM = "NEXT_PPCR_FORM";
export const SUBMIT_PPCR_FORM = "SUBMIT_PPCR_FORM";
export const FETCH_ALL_PPCR = "FETCH_ALL_PPCR";
export const RESET_PPCR = "RESET_PPCR";
export const STORE_USER_ROLES = "STORE_USER_ROLES";

// Master LoV
export const GET_ROLE = "GET_ROLE";
export const GET_MODULE = "GET_MODULE";
export const GET_SUBMODULE = "GET_SUBMODULE";
export const GET_FORM = "GET_FORM";
export const GET_ACTION = "GET_ACTION";
export const GET_MAIL_TEMPLATE = "GET_MAIL_TEMPLATE";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_MANUFACTURING_SITE = "GET_MANUFACTURING_SITE";
export const GET_SUPPLIER_LIST = "GET_SUPPLIER_LIST";
export const GET_MATERIAL_CODE = "GET_MATERIAL_CODE";
export const GET_MATERIAL_NAME = "GET_MATERIAL_NAME";
export const GET_GENERIC_NAME = "GET_GENERIC_NAME";
export const GET_MANUFACTURER = "GET_MANUFACTURER";
export const GET_SUPPLIER_NAME = "GET_SUPPLIER_NAME";
export const GET_CURRENCY = "GET_CURRENCY";
export const GET_UOM = "GET_UOM";
export const GET_JENIS_KEMASAN = "GET_JENIS_KEMASAN";
export const GET_PROMON = "GET_PROMON";

// Master User
export const GET_ALL_MASTER_USER = "GET_ALL_MASTER_USER";
export const GET_MASTER_USER_BY_ID = "GET_MASTER_USER_BY_ID";
export const GET_MASTER_USER_BY_USERNAME = "GET_MASTER_USER_BY_USERNAME";
export const POST_MASTER_USER = "POST_MASTER_USER";
export const PUT_MASTER_USER = "PUT_MASTER_USER";
export const DELETE_MASTER_USER = "DELETE_MASTER_USER";
export const RESET_USER_PASSWORD = "RESET_USER_PASSWORD";

// Master User Akses
export const GET_ALL_MASTER_USER_AKSES = "GET_ALL_MASTER_USER_AKSES";
export const GET_MASTER_USER_AKSES_BY_ID = "GET_MASTER_USER_AKSES_BY_ID";
export const POST_MASTER_USER_AKSES = "GET_MASTER_USER_AKSES";
export const PUT_MASTER_USER_AKSES = "GET_MASTER_USER_AKSES";
export const DELETE_MASTER_USER_AKSES = "DELETE_MASTER_USER_AKSES";

// Master Site Print Out
export const GET_ALL_MASTER_SITE_PRINT_OUT = "GET_ALL_MASTER_SITE_PRINT_OUT";
export const GET_MASTER_SITE_PRINT_OUT_BY_ID =
  "GET_MASTER_SITE_PRINT_OUT_BY_ID";
export const POST_MASTER_SITE_PRINT_OUT = "POST_MASTER_SITE_PRINT_OUT";
export const PUT_MASTER_SITE_PRINT_OUT = "PUT_MASTER_SITE_PRINT_OUT";
export const DELETE_MASTER_SITE_PRINT_OUT = "DELETE_MASTER_SITE_PRINT_OUT";

// Master Clustering Document
export const GET_ALL_MASTER_CLUSTERING_DOCUMENT =
  "GET_ALL_MASTER_CLUSTERING_DOCUMENT";
export const GET_MASTER_CLUSTERING_DOCUMENT_BY_ID =
  "GET_MASTER_CLUSTERING_DOCUMENT_BY_ID";
export const POST_MASTER_CLUSTERING_DOCUMENT =
  "POST_MASTER_CLUSTERING_DOCUMENT";
export const PUT_MASTER_CLUSTERING_DOCUMENT = "PUT_MASTER_CLUSTERING_DOCUMENT";
export const DELETE_MASTER_CLUSTERING_DOCUMENT =
  "DELETE_MASTER_CLUSTERING_DOCUMENT";

// Master Scoring
export const GET_ALL_MASTER_SCORING = "GET_ALL_MASTER_SCORING";
export const GET_MASTER_SCORING_BY_ID = "GET_MASTER_SCORING_BY_ID";
export const POST_MASTER_SCORING = "POST_MASTER_SCORING";
export const PUT_MASTER_SCORING = "PUT_MASTER_SCORING";
export const DELETE_MASTER_SCORING = "DELETE_MASTER_SCORING";

// Email Template
export const GET_ALL_MAIL_TEMPLATE = "GET_ALL_MAIL_TEMPLATE";
export const GET_MAIL_TEMPLATE_BY_ID = "GET_MAIL_TEMPLATE_BY_ID";
export const POST_MAIL_TEMPLATE = "POST_MAIL_TEMPLATE";
export const PUT_MAIL_TEMPLATE = "PUT_MAIL_TEMPLATE";
export const DELETE_MAIL_TEMPLATE = "DELETE_MAIL_TEMPLATE";

// Email Rule
export const GET_ALL_MAIL_RULE = "GET_ALL_MAIL_RULE";
export const GET_MAIL_RULE_BY_ID = "GET_MAIL_RULE_BY_ID";
export const POST_MAIL_RULE = "POST_MAIL_RULE";
export const PUT_MAIL_RULE = "PUT_MAIL_RULE";
export const DELETE_MAIL_RULE = "DELETE_MAIL_RULE";

// Data Master
export const GET_ALL_DATA_MASTER_GROUPED = "GET_ALL_DATA_MASTER_GROUPED";
export const GET_ALL_DATA_MASTER_HEADER = "GET_ALL_DATA_MASTER_HEADER";
export const GET_ALL_DATA_MASTER_DETAIL = "GET_ALL_DATA_MASTER_DETAIL";
export const GET_DATA_MASTER_BY_ID = "GET_DATA_MASTER_BY_ID";
export const PUT_DATA_MASTER = "PUT_DATA_MASTER";

// Data Bank Material - K-Partner
export const GET_ALL_BANK_DATA_MATERIAL_KPARTNER =
  "GET_ALL_BANK_DATA_MATERIAL_KPARTNER";
export const GET_BANK_DATA_MATERIAL_BY_ID_KPARTNER =
  "GET_BANK_DATA_MATERIAL_BY_ID_KPARTNER";
export const POST_BANK_DATA_MATERIAL_KPARTNER =
  "POST_BANK_DATA_MATERIAL_KPARTNER";
export const PUT_BANK_DATA_MATERIAL_KPARTNER =
  "PUT_BANK_DATA_MATERIAL_KPARTNER";
export const DELETE_BANK_DATA_MATERIAL_KPARTNER =
  "DELETE_BANK_DATA_MATERIAL_KPARTNER";

// Data Bank Material - Supplier
export const GET_ALL_BANK_DATA_MATERIAL_SUPPLIER =
  "GET_ALL_BANK_DATA_MATERIAL_SUPPLIER";
export const GET_BANK_DATA_MATERIAL_BY_ID_SUPPLIER =
  "GET_BANK_DATA_MATERIAL_BY_ID_SUPPLIER";
export const POST_BANK_DATA_MATERIAL_SUPPLIER =
  "POST_BANK_DATA_MATERIAL_SUPPLIER";
export const PUT_BANK_DATA_MATERIAL_SUPPLIER =
  "PUT_BANK_DATA_MATERIAL_SUPPLIER";
export const DELETE_BANK_DATA_MATERIAL_SUPPLIER =
  "DELETE_BANK_DATA_MATERIAL_SUPPLIER";

// User Profile (m-one)
export const GET_ALL_USER_PROFILE = "GET_ALL_USER_PROFILE";
export const GET_USER_PROFILE_DETAIL = "GET_USER_PROFILE_DETAIL";

// Master Material Function
export const GET_ALL_MASTER_MAT_FUNCTION = "GET_ALL_MASTER_MAT_FUNCTION";
export const GET_MASTER_MAT_FUNCTION_BY_ID = "GET_MASTER_MAT_FUNCTION_BY_ID";
export const POST_MASTER_MAT_FUNCTION = "POST_MASTER_MAT_FUNCTION";
export const PUT_MASTER_MAT_FUNCTION = "PUT_MASTER_MAT_FUNCTION";
export const DELETE_MASTER_MAT_FUNCTION = "DELETE_MASTER_MAT_FUNCTION";

// Master Target LT Sample
export const GET_ALL_MASTER_LT_SAMPLE = "GET_ALL_MASTER_LT_SAMPLE";
export const GET_MASTER_LT_SAMPLE_BY_ID = "GET_MASTER_LT_SAMPLE_BY_ID";
export const POST_MASTER_LT_SAMPLE = "POST_MASTER_LT_SAMPLE";
export const PUT_MASTER_LT_SAMPLE = "PUT_MASTER_LT_SAMPLE";
export const DELETE_MASTER_LT_SAMPLE = "DELETE_MASTER_LT_SAMPLE";

// Master Target LT Sourcing
export const GET_ALL_MASTER_LT_SOURCING = "GET_ALL_MASTER_LT_SOURCING";
export const GET_MASTER_LT_SOURCING_BY_ID = "GET_MASTER_LT_SOURCING_BY_ID";
export const POST_MASTER_LT_SOURCING = "POST_MASTER_LT_SOURCING";
export const PUT_MASTER_LT_SOURCING = "PUT_MASTER_LT_SOURCING";
export const DELETE_MASTER_LT_SOURCING = "DELETE_MASTER_LT_SOURCING";

// Master Terms and Condition
export const GET_ALL_MASTER_TERMS_CONDITION = "GET_ALL_MASTER_TERMS_CONDITION";
export const GET_MASTER_TERMS_CONDITION_BY_ID =
  "GET_MASTER_TERMS_CONDITION_BY_ID";
export const POST_MASTER_TERMS_CONDITION = "POST_MASTER_TERMS_CONDITION";
export const PUT_MASTER_TERMS_CONDITION = "PUT_MASTER_TERMS_CONDITION";

// BID RESPONSE
export const GET_ALL_BID_RESPONSE = "GET_ALL_BID_RESPONSE";
export const GET_BID_RESPONSE_BY_ID = "GET_BID_RESPONSE_BY_ID";
export const POST_BID_RESPONSE = "POST_BID_RESPONSE";
export const PUT_BID_RESPONSE = "PUT_BID_RESPONSE";
export const DELETE_BID_RESPONSE = "DELETE_BID_RESPONSE";
export const PUT_APPROVAL_BID_RESPONSE = "PUT_APPROVAL_BID_RESPONSE";
export const POST_COMMENT = "POST_COMMENT";
export const POST_NOTIFICATION = "POST_NOTIFICATION";
export const DELETE_FILE_BID_RESPONSE_BY_ID = "DELETE_FILE_BID_RESPONSE_BY_ID";
export const POST_EXPORT_EXCEL = "POST_EXPORT_EXCEL";

//Transfer Data
export const GET_ALL_TRANSFER_DATA = "GET_ALL_TRANSFER_DATA";
export const EXPORT_EXCEL_TRANSFER_DATA = "EXPORT_EXCEL_TRANSFER_DATA";

// Request Budget
export const GET_ALL_REQUEST_BUDGET = "GET_ALL_REQUEST_BUDGET";
export const GET_REQUEST_BUDGET_BY_ID = "GET_REQUEST_BUDGET_BY_ID";
export const PUT_REQUEST_BUDGET = "PUT_REQUEST_BUDGET";
export const DELETE_REQUEST_BUDGET = "DELETE_REQUEST_BUDGET";

// Master Change Category
export const GET_ALL_MASTER_CHANGE_CATEGORY = "GET_ALL_MASTER_CHANGE_CATEGORY";
export const GET_MASTER_CHANGE_CATEGORY_BY_ID =
  "GET_MASTER_CHANGE_CATEGORY_BY_ID";
export const POST_MASTER_CHANGE_CATEGORY = "POST_MASTER_CHANGE_CATEGORY";
export const PUT_MASTER_CHANGE_CATEGORY = "PUT_MASTER_CHANGE_CATEGORY";
export const DELETE_MASTER_CHANGE_CATEGORY = "DELETE_MASTER_CHANGE_CATEGORY";

//Master Supplier Document
export const GET_ALL_MASTER_SUPPLIER_DOCUMENT =
  "GET_ALL_MASTER_SUPPLIER_DOCUMENT";
export const GET_MASTER_SUPPLIER_DOCUMENT_BY_ID =
  "GET_MASTER_SUPPLIER_DOCUMENT_BY_ID";
export const POST_MASTER_SUPPLIER_DOCUMENT = "POST_MASTER_SUPPLIER_DOCUMENT";
export const PUT_MASTER_SUPPLIER_DOCUMENT = "PUT_MASTER_SUPPLIER_DOCUMENT";
export const DELETE_MASTER_SUPPLIER_DOCUMENT =
  "DELETE_MASTER_SUPPLIER_DOCUMENT";

// Master Qty per Year
export const GET_ALL_MASTER_QTY_PER_YEAR = "GET_ALL_MASTER_QTY_PER_YEAR";
export const GET_MASTER_QTY_PER_YEAR_BY_ID = "GET_MASTER_QTY_PER_YEAR_BY_ID";
export const POST_MASTER_QTY_PER_YEAR = "POST_MASTER_QTY_PER_YEAR";
export const PUT_MASTER_QTY_PER_YEAR = "PUT_MASTER_QTY_PER_YEAR";
export const DELETE_MASTER_QTY_PER_YEAR = "DELETE_MASTER_QTY_PER_YEAR";

// Master Country
export const GET_ALL_MASTER_COUNTRY = "GET_ALL_MASTER_COUNTRY";
export const GET_MASTER_COUNTRY_BY_ID = "GET_MASTER_COUNTRY_BY_ID";
export const POST_MASTER_COUNTRY = "POST_MASTER_COUNTRY";
export const PUT_MASTER_COUNTRY = "PUT_MASTER_COUNTRY";
export const DELETE_MASTER_COUNTRY = "DELETE_MASTER_COUNTRY";

// Master Function Supplier
export const GET_ALL_MASTER_FUNCTION_SUPPLIER =
  "GET_ALL_MASTER_FUNCTION_SUPPLIER";
export const GET_ALL_MASTER_FUNCTION_SUPPLIER_WITHOUT_PAGINATION =
  "GET_ALL_MASTER_FUNCTION_SUPPLIER_WITHOUT_PAGINATION";
export const GET_MASTER_FUNCTION_SUPPLIER_BY_ID =
  "GET_MASTER_FUNCTION_SUPPLIER_BY_ID";
export const POST_MASTER_FUNCTION_SUPPLIER = "POST_MASTER_FUNCTION_SUPPLIER";
export const PUT_MASTER_FUNCTION_SUPPLIER = "PUT_MASTER_FUNCTION_SUPPLIER";
export const DELETE_MASTER_FUNCTION_SUPPLIER =
  "DELETE_MASTER_FUNCTION_SUPPLIER";
export const RESET_STATE_FORM_FUNCTION = "RESET_FORM_SUPPLIER_FUNCTION";

// Suggestion Project
export const GENERATE_SUGGESTION_PROJECT = "GENERATE_SUGGESTION_PROJECT";
export const GET_ALL_SUGGESTION_PROJECT = "GET_ALL_SUGGESTION_PROJECT";
export const GET_SUGGESTION_PROJECT_BY_ID = "GET_SUGGESTION_PROJECT_BY_ID";
export const PUT_SUGGESTION_PROJECT = "PUT_SUGGESTION_PROJECT";
export const DELETE_SUGGESTION_PROJECT = "DELETE_SUGGESTION_PROJECT";
export const DOWNLOAD_SUGGESTION_PROJECT = "DOWNLOAD_SUGGESTION_PROJECT";
export const EXPORT_SUGGESTION_PROJECT = "EXPORT_SUGGESTION_PROJECT";
export const SUBMIT_SUGGESTION_PROJECT = "SUBMIT_SUGGESTION_PROJECT";
export const REVISE_SUGGESTION_PROJECT = "REVISE_SUGGESTION_PROJECT";
export const APPROVE_SUGGESTION_PROJECT = "APPROVE_SUGGESTION_PROJECT";

//Get Supplier
export const GET_ALL_SUPPLIER = "GET_ALL_SUPPLIER";
//Register Supplier
export const POST_REGISTER_SUPPLIER = "POST_REGISTER_SUPPLIER";
//My profile supplier
export const GET_MY_PROFILE_SUPPLIER_BY_ID = "GET_MY_PROFILE_SUPPLIER_BY_ID";
export const PUT_MY_PROFILE_SUPPLIER = "PUT_MY_PROFILE_SUPPLIER";
export const DOWNLOAD_SUPPLIER_LIST = "DOWNLOAD_SUPPLIER_LIST";
export const DOWNLOAD_CONTACT_PERSON_LIST = "DOWNLOAD_CONTACT_PERSON_LIST";
//Get Supplier Detail
export const GET_SUPPLIER_DETAIL = "GET_SUPPLIER_DETAIL";

//Monitoring Contract
export const GET_ALL_MONITORING_CONTRACT = "GET_ALL_MONITORING_CONTRACT";

//Inquiry
export const GET_ALL_INQUIRY = "GET_ALL_INQUIRY";
export const GET_ALL_INQUIRY_GROUPED = "GET_ALL_INQUIRY_GROUPED";
export const GET_INQUIRY_BY_ID = "GET_INQUIRY_BY_ID";
export const POST_INQUIRY = "POST_INQUIRY";
export const PUT_INQUIRY = "PUT_INQUIRY";
export const DELETE_INQUIRY = "DELETE_INQUIRY";
export const GET_INQUIRY_SUPPLIER_NAME = "GET_INQUIRY_SUPPLIER_NAME";

//Inquiry Response
export const GET_ALL_INQUIRY_RESPONSE = "GET_ALL_INQUIRY_RESPONSE";
export const GET_ALL_INQUIRY_RESPONSE_GROUPED =
  "GET_ALL_INQUIRY_RESPONSE_GROUPED";
export const GET_INQUIRY_RESPONSE_BY_ID = "GET_INQUIRY_RESPONSE_BY_ID";
export const POST_INQUIRY_RESPONSE = "POST_INQUIRY_RESPONSE";
export const PUT_INQUIRY_RESPONSE = "PUT_INQUIRY_RESPONSE";
export const DELETE_INQUIRY_RESPONSE = "DELETE_INQUIRY_RESPONSE";

// Request Sourcing
export const GET_ALL_REQUEST_SOURCING = "GET_ALL_REQUEST_SOURCING";
export const GET_REQUEST_SOURCING = "GET_REQUEST_SOURCING";
export const POST_REQUEST_SOURCING = "POST_REQUEST_SOURCING";
export const PUT_REQUEST_SOURCING = "PUT_REQUEST_SOURCING";
export const DELETE_REQUEST_SOURCING = "DELETE_REQUEST_SOURCING";
export const GET_LAST_REQUEST_SOURCING = "GET_LAST_REQUEST_SOURCING";
export const SUBMIT_REQUEST_SOURCING = "SUBMIT_REQUEST_SOURCING";
export const APPROVE_REQUEST_SOURCING = "APPROVE_REQUEST_SOURCING";
export const REJECT_REQUEST_SOURCING = "REJECT_REQUEST_SOURCING";
export const REVISE_REQUEST_SOURCING = "REVISE_REQUEST_SOURCING";
export const ASSIGN_REQUEST_SOURCING = "ASSIGN_REQUEST_SOURCING";

// Material Sample Request
export const GET_ALL_SAMPLE_REQUEST = "GET_ALL_SAMPLE_REQUEST";
export const GET_SAMPLE_REQUEST_BY_ID = "GET_SAMPLE_REQUEST_BY_ID";
export const POST_SAMPLE_REQUEST = "POST_SAMPLE_REQUEST";
export const PUT_SAMPLE_REQUEST = "PUT_SAMPLE_REQUEST";
export const DELETE_SAMPLE_REQUEST = "DELETE_SAMPLE_REQUEST";
export const EXPORT_SAMPLE_REQUEST = "EXPORT_SAMPLE_REQUEST";
export const SUBMIT_SAMPLE_REQUEST = "SUBMIT_SAMPLE_REQUEST";
export const REVISE_SAMPLE_REQUEST = "REVISE_SAMPLE_REQUEST";
export const APPROVE_SAMPLE_REQUEST = "APPROVE_SAMPLE_REQUEST";
export const REJECT_SAMPLE_REQUEST = "REJECT_SAMPLE_REQUEST";

//Master PM Type
export const GET_ALL_MASTER_PM_TYPE = "GET_ALL_MASTER_PM_TYPE";
export const GET_MASTER_PM_TYPE_BY_ID = "GET_MASTER_PM_TYPE_BY_ID";
export const POST_MASTER_PM_TYPE = "POST_MASTER_PM_TYPE";
export const PUT_MASTER_PM_TYPE = "PUT_MASTER_PM_TYPE";
export const DELETE_MASTER_PM_TYPE = "DELETE_MASTER_PM_TYPE";
export const GET_MATERIAL_TYPE = "GET_MATERIAL_TYPE";

//Master Material Code
export const GET_ALL_MASTER_MATERIAL_CODE = "GET_ALL_MASTER_MATERIAL_CODE";
export const GET_MASTER_MATERIAL_CODE_BY_ID = "GET_MASTER_MATERIAL_CODE_BY_ID";
export const POST_MASTER_MATERIAL_CODE = "POST_MASTER_MATERIAL_CODE";
export const PUT_MASTER_MATERIAL_CODE = "PUT_MASTER_MATERIAL_CODE";
export const DELETE_MASTER_MATERIAL_CODE = "DELETE_MASTER_MATERIAL_CODE";

//Master Job List
export const GET_ALL_MASTER_JOB_LIST = "GET_ALL_MASTER_JOB_LIST";
export const GET_MASTER_JOB_LIST_BY_ID = "GET_MASTER_JOB_LIST_BY_ID";
export const POST_MASTER_JOB_LIST = "POST_MASTER_JOB_LIST";
export const PUT_MASTER_JOB_LIST = "PUT_MASTER_JOB_LIST";
export const DELETE_MASTER_JOB_LIST = "DELETE_MASTER_JOB_LIST";

// Close Project
export const GET_ALL_CLOSE_PROJECT_LIST = "GET_ALL_CLOSE_PROJECT_LIST";
export const GET_CLOSE_PROJECT_LIST_BY_ID = "GET_CLOSE_PROJECT_LIST_BY_ID";
export const GET_PLM_DATA_CC = "GET_PLM_DATA_CC";
export const GET_PLM_DATA_JIP = "GET_PLM_DATA_JIP";
export const POST_CLOSE_PROJECT_LIST = "POST_CLOSE_PROJECT_LIST";
export const PUT_CLOSE_PROJECT_LIST = "PUT_CLOSE_PROJECT_LIST";
export const DELETE_CLOSE_PROJECT_LIST = "DELETE_CLOSE_PROJECT_LIST";
export const EXPORT_CLOSE_PROJECT_LIST = "EXPORT_CLOSE_PROJECT_LIST";

//  Material Review
export const GET_MATERIAL_REVIEW_NO = "GET_MATERIAL_REVIEW_NO ";

// Change PIC
export const GET_ALL_DOCUMENT_CREATOR_LIST = "GET_ALL_DOCUMENT_CREATOR_LIST";
export const GET_DOCUMENT_APPROVAL = "GET_DOCUMENT_APPROVAL";
export const POST_CHANGE_PIC = "POST_CHANGE_PIC";

// Transfer Document
export const GET_ALL_TRANSFER_DOCUMENT = "GET_ALL_TRANSFER_DOCUMENT";
export const GET_TRANSFER_DOCUMENT = "GET_TRANSFER_DOCUMENT";
export const POST_TRANSFER_DOCUMENT = "POST_TRANSFER_DOCUMENT";
export const PUT_TRANSFER_DOCUMENT = "PUT_TRANSFER_DOCUMENT";
export const DELETE_TRANSFER_DOCUMENT = "DELETE_TRANSFER_DOCUMENT";
export const EXPORT_TRANSFER_DOCUMENT = "EXPORT_TRANSFER_DOCUMENT";
export const SUBMIT_TRANSFER_DOCUMENT = "SUBMIT_TRANSFER_DOCUMENT";
export const APPROVE_TRANSFER_DOCUMENT = "APPROVE_TRANSFER_DOCUMENT";
export const RECEIVE_TRANSFER_DOCUMENT = "RECEIVE_TRANSFER_DOCUMENT";
export const REVISE_TRANSFER_DOCUMENT = "REVISE_TRANSFER_DOCUMENT";
export const FEEDBACK_RECEIVER_TRANSFER_DOCUMENT = "FEEDBACK_RECEIVER_TRANSFER_DOCUMENT";
export const FEEDBACK_SOURCING_SPV_TRANSFER_DOCUMENT = "FEEDBACK_SOURCING_SPV_TRANSFER_DOCUMENT";

// Intern
export const GET_ALL_INTERN = "GET_ALL_INTERN";
export const GET_INTERN_BY_ID = "GET_INTERN_BY_ID";
export const POST_INTERN = "POST_INTERN";
export const PUT_INTERN = "PUT_INTERN";
export const DELETE_INTERN = "DELETE_INTERN";

// Mentor
export const GET_ALL_MENTOR = "GET_ALL_MENTOR";
export const GET_MENTOR_BY_ID = "GET_MENTOR_BY_ID";
export const POST_MENTOR = "POST_MENTOR";
export const PUT_MENTOR = "PUT_MENTOR";
export const DELETE_MENTOR = "DELETE_MENTOR";
