export const ConstListFC = {
  SET_DATA: "FORECAST_CALCULATION_SET_DATA",
  SET_FILTER: "FORECAST_CALCULATION_SET_FILTER",
  FAILED: "FORECAST_CALCULATION_FAILED",
  CLEAR: "FORECAST_CALCULATION_CLEAR",
  LOADING: "FORECAST_CALCULATION_LOADING",
};
