export const ConstContractApproval = {
  SET_DATA: "CONTRACT_APPROVAL_SET_DATA",
  SET_FILTER: "CONTRACT_APPROVAL_SET_FILTER",
  FAILED: "CONTRACT_APPROVAL_FAILED",
  CLEAR: "CONTRACT_APPROVAL_CLEAR",
  LOADING: "CONTRACT_APPROVAL_LOADING",
};

export const ConstDetailContractApproval = {
  SET_DATA: "DETAIL_CONTRACT_APPROVAL_SET_DATA",
  SET_FILTER: "DETAIL_CONTRACT_APPROVAL_SET_FILTER",
  FAILED: "DETAIL_CONTRACT_APPROVAL_FAILED",
  CLEAR: "DETAIL_CONTRACT_APPROVAL_CLEAR",
  LOADING: "DETAIL_CONTRACT_APPROVAL_LOADING",
};
