export const ConstListPA = {
  SET_DATA: "PROGRESS_APPROVAL_SET_DATA",
  SET_FILTER: "PROGRESS_APPROVAL_SET_FILTER",
  FAILED: "PROGRESS_APPROVAL_FAILED",
  CLEAR: "PROGRESS_APPROVAL_CLEAR",
  LOADING: "PROGRESS_APPROVAL_LOADING",
};
