export const ConstMaterialReview = {
  SET_DATA: "MATERIAL_REVIEW_SET_DATA",
  SET_FILTER: "MATERIAL_REVIEW_SET_FILTER",
  FAILED: "MATERIAL_REVIEW_FAILED",
  CLEAR: "MATERIAL_REVIEW_CLEAR",
  LOADING: "MATERIAL_REVIEW_LOADING",
};
