export const ConstBidComparison = {
  SET_DATA: "BID_COMPARISON_SET_DATA",
  SET_FILTER: "BID_COMPARISON_SET_FILTER",
  FAILED: "BID_COMPARISON_FAILED",
  CLEAR: "BID_COMPARISON_CLEAR",
  LOADING: "BID_COMPARISON_LOADING",
};
