export const ConstListSC = {
  SET_DATA: "SUGGESTION_CONTRACT_SET_DATA",
  SET_FILTER: "SUGGESTION_CONTRACT_SET_FILTER",
  FAILED: "SUGGESTION_CONTRACT_FAILED",
  CLEAR: "SUGGESTION_CONTRACT_CLEAR",
  LOADING: "SUGGESTION_CONTRACT_LOADING",
};
